### ISSUE TITLE
R toolbox: setSimulationTime fails if number of time interval is changed

### ISSUE THREAD

**Issue by CandideThunder** [Open-Systems-Pharmacology/R-Toolbox#10] opened 2017-05-10 12:27 UTC
`setSimulationTime `can be used to set one or several simulation time intervals. If the simulation contains e.g. 2 intervals, and that is overwritten to 1 interval, processSimulation fails.

See attached example code.
[tests.zip](https://github.com/Open-Systems-Pharmacology/R-Toolbox/files/989694/tests.zip)

```
simModelXML <- "./models/black american girl.xml"
dci_info <- initSimulation(XML=simModelXML, whichInitParam="none")
length (dci_info$InputTab$TimeSchema$StartTime) #2 -> two different time intervals

processSim

ulation(DCI_Info=dci_info) # works!

dci_info <- setSimulationTime(c(1:60, timepoints=(0:7)*60), DCI_Info=dci_info) # two different time intervals
processSimulation(DCI_Info=dci_info) # works!

dci_info <- setSimulationTime(c(1:60), DCI_Info=dci_info) # one time interval
processSimulation(DCI_Info=dci_info) # not working!

# Error in processSimulation(DCI_Info = dci_info) : 
#   Unknown interval distribution type passed: 


```

**Comment by PavelBal** [comment] 2017-09-18 08:41
Any progress on this?

**Comment by StephanSchaller** [comment] 2018-01-13 10:23
Yes, any News?

**Comment by StephanSchaller** [comment] 2018-01-13 11:47
So I had the same. It only gives the error when gowing to a lower number of time intervals (as above from 2 -> 1) but not when increasing number of time intervals (1 -> 2).

`h <- .Call("RDCI_ProcessData", as.integer(DCI_Info$Handle),  as.integer(1)) ` in `processSimulation` then Fails 👀

**Comment by StephanSchaller** [comment] 2018-01-15 00:13
Upvoting Priority!

**Comment by msevestre** [comment] 2018-01-15 00:18
@stephanschaller PR (pull request) welcomed. This is definitely something that the community could / should implement

**Comment by StephanSchaller** [comment] 2018-01-15 01:32
This is not a bug in R Code! This is a bug within the RDCI call!

**Comment by StephanSchaller** [comment] 2018-01-15 01:34
The time Schema in the DCI_Info data.frame is correctly set!

**Comment by msevestre** [comment] 2018-01-15 02:10
I see.
@Yuri05 would it be feasible to move DCIR to github?

@StephanSchaller in the meantime and as a workaround, can you set the second interval to an empty vector? e.g. instead of decreasing the number of intervals, simply making one of them irrelevant 

Would that work?

**Comment by StephanSchaller** [comment] 2018-01-15 08:57
@msevestre Thank, you!

I'll check.

**Comment by msevestre** [comment] 2018-01-15 13:59
@all: Looking at this function, one does not define `time intervals` but simply time points (e.g a vector of time values). Is this correct? 
So the issue happens when reducing the number of points in the array?

**Comment by StephanSchaller** [comment] 2018-01-15 16:37
@msevestre  Not exactly. setSimulationTime checks for equidistant time sequences. Let'e say:

`TimeSeq <- seq(0,12,1) # in Matlab: TimeSeq = 0:12`
Thats one equidistant sequence. For this `dci_info <- setSimulationTime(TimeSeq, dci_info)` enters characteristics into the `DCI_Info$InputTab$TimeSchema`. There is `TimeSchema$StartTime, TimeSchema$EndTime, TimeSchema$NoOfTimePoints and... TimeSchema$Distribution`.

For above sequence you get:

```
DCI_Info$InputTab$TimeSchema...
TimeSchema$StartTime[1] = 0
TimeSchema$EndTime[1] = 12
TimeSchema$NoOfTimePoints[1] = 13
TimeSchema$Distribution[1] = "Equidistant"
```
If you set `TimeSeq <- c(seq(0,12,1), seq(14,24,2)) # Matlab [0:12 14:2:24] ` and call `dci_info <- setSimulationTime(TimeSeq, dci_info)` , you get:
```
DCI_Info$InputTab$TimeSchema...
TimeSchema$StartTime[1:2] = 0 14
TimeSchema$EndTime[1:2] = 12 24
TimeSchema$NoOfTimePoints[1:2] = 13 5
TimeSchema$Distribution[1:2] = "Equidistant" "Equidistant"
```
Now if you set the first sequence (`TimeSeq <- seq(0,12,1)`) again, and you will get above error. Even though the `TimeSchema$Distribution[1] = "Equidistant"` is correctly set.

You can reduce the second sequence to 1 interval (`TimeSeq <- c(seq(0,12,1), seq(14,16,2))`) and not receive the error, but not to length 0 (`TimeSeq <- c(seq(0,12,1), seq(14,14,2))`). Reducing to length 0 will also result in only one distribution entry in the `dci_info` (`TimeSchema$Distribution[1] = "Equidistant"`) and produce the error.

So it is somewhere on the C side of Things ...

**Comment by msevestre** [comment] 2018-01-15 19:14
Thanks for your input @StephanSchaller 

So let me get that straight :-)

The code is creating intervals based on the given time point values.

e.g. seq(0,12,1) is going to create an interval starting g at 0 ending at 12 and with 13 points between 0 and 12... Is this correct?

Is this common to do stuff like that in R? Why would not someone want to pass the interval directly? Alternatively, the core engine also supports a discrete list of points which seems to be the input of the function. Why should not we pass that directly instead of creating intervals underneath the hodd?

Also as an addition
`c(1:60, timepoints=(0:7)*60` will create 3 INTERVALS and not 2

```
[1] "1 60 60"
[1] "0 120 2"
[1] "180 420 5"
```

**Comment by StephanSchaller** [comment] 2018-01-15 19:43
> `c(1:60, timepoints=(0:7)*60)` will create 3 INTERVALS and not 2 <

Strange, for me it creates two:
![image](https://user-images.githubusercontent.com/25477643/34958943-4e979c7e-fa34-11e7-828d-430d6e2b3680.png)

But in any case, it looks like this time pattern distribution code thingy in R was pretty much just translated from the Matlab MoBiToolbox (extract from `addTimePattern` in `setSimulationTime`):

```
% set new lines
for iCol=1:length(DCI_INFO{simulationIndex}.InputTab(iTab).Variables)
    switch DCI_INFO{simulationIndex}.InputTab(iTab).Variables(iCol).Name
        case 'StartTime'
            DCI_INFO{simulationIndex}.InputTab(iTab).Variables(iCol).Values(end+1)=startTime;
        case 'EndTime'
            DCI_INFO{simulationIndex}.InputTab(iTab).Variables(iCol).Values(end+1)=endTime;
        case 'NoOfTimePoints'
            DCI_INFO{simulationIndex}.InputTab(iTab).Variables(iCol).Values(end+1)=noOfTimePoints;
        case 'Distribution'
            DCI_INFO{simulationIndex}.InputTab(iTab).Variables(iCol).Values{end+1}='Equidistant';
        case 'Unit' 
            DCI_INFO{simulationIndex}.InputTab(iTab).Variables(iCol).Values{end+1}=baseUnit;
    end
end
```

and there it seems to work fine?

**Comment by StephanSchaller** [comment] 2018-01-16 03:08
If you work for a while and then call `saveSimulationToXML` and reload (initialize) the saved xml, you can see all the TimeSchema junk it has accumulated:

![image](https://user-images.githubusercontent.com/25477643/34970109-bf2bb73e-fa72-11e7-94a6-9b5c193ac669.png)

Maybe this helps. Its just not overwriting correctly during RDCI calls...

**Comment by msevestre** [comment] 2018-01-16 03:52
Unrelated to the issue but what IDE are you using? I like the color.

DCIR is the culprit. Good find!

**Comment by StephanSchaller** [comment] 2018-01-16 04:34
It's easier on the eyes, when working through the night...

It's the "Cobalt" eitor theme from RStudio.

**Comment by PavelBal** [comment] 2018-03-06 15:49
To summarize:

1) If a simulation has more than one time interval and was initialized,
2) Changing simulation time to one interval results in the error described above.

I tried to track down to the point where it happens. First of all - the R code seems to be right, calling `setSimulationTime()` with one time interval creates a correct DCI_Info table.

The problem seems to happen here: https://github.com/Open-Systems-Pharmacology/OSPSuite.SimModel/blob/12d6a23cde8da8a76e3e7737d069b5ff3ae77ccb/src/OSPSuite.SimModelComp/src/SimModelComp.cpp#L680-L693

```
	for(int intervalIdx=1; intervalIdx<=hTab->GetRecords()->GetCount(); intervalIdx++)
	{
		double startTime       = hTab->GetValue(intervalIdx, conStartTime);
		double endTime         = hTab->GetValue(intervalIdx, conEndTime);
		int numberOfTimePoints = hTab->GetValue(intervalIdx, conNoOfTimePoints);

		OutputIntervalDistribution pointsDistribution = IntervalDistributionFromString(
			                     hTab->GetValue(intervalIdx, conDistribution));

		OutputInterval * interval = new OutputInterval
			(startTime, endTime, numberOfTimePoints, pointsDistribution);

		outSchema.OutputIntervals().push_back(interval);
	}
```

Though only one interval is provided, the loop is executed twice! I.e., `hTab->GetRecords()->GetCount()` returns 2. This second "interval" does not contain any information necessary for the execution of the code, so the program crashes. Problem is, `DCI::ITableHandle hTab  = hPort->GetTable();` is from DCI6_1.dll and I cannot see into it.

Please assist, or at least provide a debug-version of DCI6_1.dll.

**Comment by PavelBal** [comment] 2018-04-04 10:02
Testing with this code:

```
simModelXML <- "d:/Work/OSPS/esqLABS/R-Toolbox/tests/models/black american girl.xml";
standard_dci_info <- initSimulation(XML=simModelXML, whichInitParam="none");

  dci_info <- standard_dci_info;
  #first 8 hours hourly 
  timepoints <- c((0:7)*60);
  dci_info <- setSimulationTime(c(1:60, timepoints=(0:7)*60), DCI_Info=dci_info);
  processSimulation(DCI_Info=dci_info);
  
  dci_info <- setSimulationTime(c(1:60), DCI_Info=dci_info);
  print("Process simulation with buggy timepoints")
  processSimulation(DCI_Info=dci_info)
```

results in

```
Error in processSimulation(DCI_Info = dci_info) : 
  Unknown interval distribution type passed: 
```

Doing the same in Matlab:

```
simModelXML = 'd:\Work\OSPS\esqLABS\R-Toolbox\tests\models\black american girl.xml';
standard_idx = 1;
initSimulation(simModelXML, 'none', 'addFileAtIndex', standard_idx);

%first 8 hours hourly 
  timepoints = [(0:7)*60];
  setSimulationTime([(1:60), timepoints], standard_idx);
  processSimulation(standard_idx)
  
  setSimulationTime([1:60], standard_idx)
  processSimulation(standard_idx)
```

works.

As pointed out, 
`
	DCI::IPortHandle  hPort = GetInputPorts()->Item(conTabOutputSchema);`

returns the lenght of 2 for R and 1 for Matlab after changing the simulation time schema and calling "ProcessData".

Before calling "ProcessData", both Matlab and R call "SetInputTable", which should also update the time schema table in the DCI. At this point, simulation time schema in DCI_INFO within R has only one entry.

My guess is that "SetInputTable" in DCIR does not update the underlying DCI correctly. Tracking down to Converstion.cpp in DCIR, lines 652-653:

```
	for (unsigned int i=0; i<varSize; i++)
		FillDCIVarFromRVar(hTab->GetColumns()->Item(i+1), VECTOR_ELT(RTable, i));
```

In `FillDCIVarFromRVar`, lines 562-566, parent table is changed if it has less entries than the passed R-Object, but not the other way arout:

```
	unsigned int valuesSize = length(RVariable);
	
	//redim parent table if required
	if (recordBased && (hTab->GetRecords()->GetCount() < valuesSize))
		hTab->ReDim(valuesSize, hTab->GetColumns()->GetCount());
```

Could it be the problem? It is only a guess as I cannot compile DCIR, not check how it is implemented in Matlab.

**Comment by Yuri05** [comment] 2020-02-10 07:38
Closing in favor of the new R-Toolbox.

**Closed as completed by Yuri05** 2020-02-10 07:38 UTC
Labels: rejected, type: bug
