### ISSUE TITLE
OSPSuite.Schema.xsd missing from package.

### ISSUE THREAD

**Issue by mark0935git** [Open-Systems-Pharmacology/R-Toolbox#69] opened 2018-05-17 07:05 UTC
Hi MoBiToolboxForR developer

I would like to know where I can find the MoBiToolboxForR.zip file in Open Systems Pharmacology Suite v7.2.2 installation folder?

Thanks

**Comment by PavelBal** [comment] 2018-05-17 07:56
By default, it is in the 

"c:\Program Files (x86)\Open Systems Pharmacology\MoBi Toolbox for R 7.2\"

**Comment by mark0935git** [comment] 2018-05-17 07:58
But I do not have that folder. The folders within Open Systems Pharmacology\ are: PK-Sim 7.2, MoBi 7.2, and InstallationValidator 7.2.

**Comment by PavelBal** [comment] 2018-05-17 08:01
OK, then it is a bug the core team has to fix...

In the meantime - https://github.com/Open-Systems-Pharmacology/R-Toolbox/releases

**Comment by mark0935git** [comment] 2018-05-17 08:05
Thanks a lot for your help!

One more question:  Can I install this zip file in R independent from Open Systems Pharmacology suite?

**Comment by PavelBal** [comment] 2018-05-17 08:17
> One more question: Can I install this zip file in R independent from Open Systems Pharmacology suite?

In theory - yes. However, you need to manually install (if not already installed) the[ Visual C++ Redistributable for Visual Studio 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48145) in order to be able to load the library.

If you try - please give your feedback here. I have problems installing the official toolbox on a clean machine with PK-Sim.

**Comment by PavelBal** [comment] 2018-05-17 08:21
And, you need the x86-version of C++ redist.

**Comment by mark0935git** [comment] 2018-05-17 08:52
My plan is to install it on a Linux workstation. I will also give a try on a clean window machine.

**Comment by PavelBal** [comment] 2018-05-17 09:04
I see. I am not sure the Toolbox will work on Linux as it comes along with some C++ libraries compiled for Windows. I can guess that these libraries must be re-compiled for Linux.

Though the solution may not exists yet, having a Linux-version of the toolbox is definitely an important feature.

**Comment by mark0935git** [comment] 2018-05-17 09:15
Thanks for letting me know! I will try to install the toolbox on a clean window machine and return you the feedback.
Definitely, it would be great to have the toolbox compatible in Linux in the future.

**Comment by msevestre** [comment] 2018-05-17 11:39
@Marc0935 How did you install the suite? 
I have just tried to install 7.2.2 on a fresh windows machine as well as on a machine with a previous install of the suite (7.2.1) and I cannot reproduce the issue.

**Comment by msevestre** [comment] 2018-05-17 11:40
@PavelBal 
> I have problems installing the official toolbox on a clean machine with PK-Sim.

Can you explain what's the issue? Or is this already documented somewhere?

**Comment by PavelBal** [comment] 2018-05-17 11:47
@msevestre 
> Can you explain what's the issue? Or is this already documented somewhere?

Fresh Win10 + R 3.4 + RStudio + OSPS 7.2.2. Installed to 7.2.0 toolbox on R 3.4. Trying to load it fails with: 
```
Error: package or namespace load failed for ‘MoBiToolboxForR’ in inDL(x, as.logical(local), as.logical(now), ...):
 unable to load shared object 'C:/Users/esqLABS/Documents/R/win-library/3.4/MoBiToolboxForR/libs/i386/DCIR6_0.dll':
  LoadLibrary failure:  The specified module could not be found.
```

btw (another issue): the toolbox needs to be re-compiled with R 3.5 to run under 3.5.

**Comment by msevestre** [comment] 2018-05-17 12:16
@PavelBal Can you create another issue for that?
Also please specify in the issue if `C:/Users/esqLABS/Documents/R/win-library/3.4/MoBiToolboxForR/libs/i386/DCIR6_0.dll` is actually defined there

**Comment by mark0935git** [comment] 2018-05-17 18:05
@msevestre @PavelBal My bad, the folder 'MoBi Toolbox for R 7.2' appears after reinstalling the suite. 

I have also tried to install the R toolbox independent from suite on a clean win machine. The installation was successful and I can also require the package.

But the following error pop up when running the microtest script

Error in initSimulation(XML = simModelXML, whichInitParam = "none") : 
  Loading of XML file "C:/R_Package/R-3.4.3/library/MoBiToolboxForR/libs/i386\OSPSuite.SimModel.xsd" failed: 
Error code: -2146697210
Url: C:/R_Package/R-3.4.3/library/MoBiToolboxForR/libs/i386\OSPSuite.SimModel.xsd
Source Text: 
At line: 0
At line Pos: 0
Reason: The system cannot locate the object specified.

**Comment by msevestre** [comment] 2018-05-17 18:18
@Marc0935 Do you have the suite installed on this machine as well?
The setup installs some required libraries to load the models and schema. 

Also can you confirm that the file `C:/R_Package/R-3.4.3/library/MoBiToolboxForR/libs/i386\OSPSuite.SimModel.xsd` is present?

**Comment by mark0935git** [comment] 2018-05-18 07:16
@msevestre 
I did not install the suite for this task, because @PavelBal would like me to test whether the R toolbox works independently from the suite or not. Apparently, it is not.

I also check the files in C:/R_Package/R-3.4.3/library/MoBiToolboxForR/libs/i386/. I did not find OSPSuite.SimModel.xsd

**Comment by msevestre** [comment] 2018-05-18 14:10
@Marc0935 I see. Ok this is a bug and will be fixed in the upcoming 7.3 version of the toolbox

**Comment by msevestre** [comment] 2018-05-18 14:11
I have allow myself to rename the entry so that we can remember what the  issue is about

**Comment by msevestre** [comment] 2018-05-18 14:52
I just realized that this was fixed already a while ago
https://github.com/Open-Systems-Pharmacology/R-Toolbox/issues/26

**Closed as completed** 2018-05-18 14:52 UTC
Labels: duplicate
